### ISSUE TITLE
Allow downstream controller to provide a layout

### ISSUE THREAD

**Issue by jcoyne** [voormedia/flipflop#18]
I'm wondering about this change:

https://github.com/voormedia/flipflop/commit/d5c7c3d6cbb43f0668a2a2a4919afafc8d2fbbf9

Previously I was able to provide a layout by doing: 
```ruby
  module MySite
    class FeaturesController < Flipflop::FeaturesController
      layout 'my_layout'
    end
  end
```

But now, this isn't working due to `render(layout: false)`.  Would it be possible to just use `render` there?

**Comment by rolftimmermans** [comment]
I will check if this can be enabled – this was changed because Rails API projects do not support layouts.

**Comment by jcoyne** [comment]
@rolftimmermans if that won't work, can we extract that to a `render_options` method that we can easily override?
