### ISSUE TITLE
Easily override features per environment? 

### ISSUE THREAD

**Issue by alex-hall** [voormedia/flipflop#22]
I'm trying to understand how to programmatically override a feature flag. My use case is that in development i'd like certain features to always be on (Not using the UI). 

During test, we have  accomplished this using the config shown in the readme: 

```ruby
    test_strategy = Flipflop::FeatureSet.current.test!
    test_strategy.switch!(:world_domination, true)
```

But there doesn't seem to be any other available strategies to switch features at runtime (in dev, acceptance, etc). Looking at how the Flipflop UI does it, it looks like there is some cache manipulation happening along side the actual manipulation of the status, so I didn't want to duplicate that code in my codebase. 

Is there a recommended way of doing this that i'm missing?

**Comment by rolftimmermans** [comment]
Does it work for you to set the `default` flag differently per environment? Like this:

```
Flipflop.configure do
  # (omitted strategies here)
  feature :world_domination, default: !Rails.env.production?
end
```

Or do you need to have different strategies per environment – for example `database` for production and something else for development?

**Comment by alex-hall** [comment]
I think that would suffice for my use case. I was just wondering if there was a simple command like:

```ruby
Flipflop::FeatureSet.<WHATEVER_CURRENT_ENV_IS>.switch!(:some_configuration, true)
```

**Comment by rolftimmermans** [comment]
You can still do this, if you want, even in development:

```
test_strategy = Flipflop::FeatureSet.current.test!
test_strategy.switch!(:world_domination, true)
```

All it does is replace all strategies with a single mock strategy that allows you to easily programmatically flip feature switches.

**Comment by JPrevost** [comment]
This seems to work well if you are already using ENV for setting config level stuff:

```
Flipflop.configure do
  # (omitted strategies here)
  feature :world_domination, default: ENV['WORLD_DOMINATION']
end
```
