### ISSUE TITLE
ActionView::MissingTemplate in Flipflop::Features#index in Rails 7

### ISSUE THREAD

**Issue by mldoscar** [voormedia/flipflop#39]
Hello. We're experiencing this exception after Rails 7.0.2 upgrade, even using latest flipflop gem (2.6.0), and also same behavior using master branch.

Example for repeating the error: `https://github.com/mldoscar/flipflop-issue-on-r7-example`

Our application mounts the Flipflop engine in `routes.rb` like this:
```ruby
Rails.application.routes.draw do
  mount Flipflop::Engine => '/flipflop'
end
```

Then when I try to surf to this address `localhost:3000/flipflop` the following exception is raised:
```ruby
ActionView::MissingTemplate in Flipflop::Features#index

Missing partial flipflop/stylesheets/_flipflop.css with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}.
```
We're aware that starting from Rails 7, rendering files with extension would cause an exception. Does anyone else is experiencing this issue?

Ruby: 2.7.4
Rails: 7.0.2.3
RVM: 1.29.12

Also i'm going to submit a PR in order to expect feedback if it's the best way to solve this issue

**Comment by leoarnold** [comment]
Fixed by #40. Released in `v2.7.0`.
