### ISSUE TITLE
Can config file location be settable?

### ISSUE THREAD

**Issue by jcoyne** [voormedia/flipflop#4]
I'd like to use flipflop within a Rails engine.  I'd like the `config/features.rb` file to reside within the engine too (so that we can add features in the future). So I'd like to be able to change https://github.com/voormedia/flipflop/blob/master/lib/flipflop/engine.rb#L17

Should I write a PR to set the file path as a `class_attribute` on `Flipflop::Engine`?

**Comment by rolftimmermans** [comment]
This is now possible. See #6 for more details.

**Comment by jcoyne** [comment]
Thanks so much. I just tested this and it's working great! 👏
