### ISSUE TITLE
Is the dependency on bootstrap 4.0.0.alpha intentional?

### ISSUE THREAD

**Issue by jcoyne** [voormedia/flipflop#5]
I'm not sure I understand why it's required here, when `ENV["CONTINUOUS_INTEGRATION"]` is false:
https://github.com/voormedia/flipflop/blob/master/flipflop.gemspec#L20

but here when `ENV["CONTINUOUS_INTEGRATION"]` is true:
https://github.com/voormedia/flipflop/blob/master/Gemfile#L5

**Comment by rolftimmermans** [comment]
Bootstrap is only required during development. When released it's removed from the dependencies, so that the gem on Rubygems does not have a bootstrap dependency. But in order to release it, it's still needed to compile the SCSS, so that is why it is required in the Gemfile for CI and release.
