### ISSUE TITLE
Pair back the build matrix?

### ISSUE THREAD

**Issue by jcoyne** [voormedia/flipflop#8]
There are currently 34 builds (❗) in the matrix.  Can we remove Rails 4.0 and Rails 4.1? They are no longer supported by the Rails core team.  Do you know of anyone who has requested that flipflop be tested on those platforms?

**Comment by rolftimmermans** [comment]
Good point – I've removed 4.0, but I'd like to keep 4.1 around for a bit. There are some applications that we have that are still on 4.1.
